import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar />
        <main className='w-[calc(100%-90px)] max-w-[690px] m-auto'>
        {children}
        </main>        
        </body>
    </html>
  )
}
