import './globals.css'
import Navbar from '@/components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        
        <main className='bg-gray-50 min-h-screen'>
        <Navbar />
        {children}
        </main>
        
        </body>
    </html>
  )
}
